pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                echo 'Kod çekiliyor...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Build ediliyor...'
                dir('Not-App') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                echo 'Birim testler...'
                dir('Not-App') {
                    bat 'mvn test'
                }
            }
            post {
                always {
                    dir('Not-App') {
                        junit '**/target/surefire-reports/*.xml'
                    }
                }
            }
        }

        stage('Integration Tests') {
            steps {
                echo 'Entegrasyon testleri...'
                dir('Not-App') {
                    bat 'mvn verify'
                }
            }
            post {
                always {
                    dir('Not-App') {
                        junit '**/target/failsafe-reports/*.xml'
                    }
                }
            }
        }

stage('5 - Run System in Docker') {
    steps {
        echo '========== Docker Compose ile sistem ayağa kaldırılıyor =========='


            powershell(script: '''
                $ErrorActionPreference = "Stop"

                Write-Host "== Önceki container'lar temizleniyor =="
                try {
                    docker compose -f docker-compose.yml down -v
                } catch {
                    Write-Host "Önceki container yok, devam ediliyor"
                }

                Write-Host "== DB ve Backend ayağa kaldırılıyor =="
                docker compose -f docker-compose.yml up -d --build

                Write-Host "== Container durumları =="
                docker compose -f docker-compose.yml ps
            ''')
    }
}



    }
}
